### ISSUE TITLE
Remove fieldset re-order snippet

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Snippet-Library#17]
@DevinWalker in testing this snippet:
https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/customize-fieldset-order.php

It looks like it just breaks the form unless you do the tiniest of re-ordering. If you try to do anything meaningful with it, the payment gateway selector breaks.

I'd suggest deleting it for now until we get the new form markup API finished.

**Comment by DevinWalker** [comment]
I'm fine with removing it.
