### ISSUE TITLE
Differentiating Snippet Library from Actions/Filters Docs

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Snippet-Library#2]
We need to have a clear distinction between what goes in the Snippet Library and what goes in our Actions/Filters docs. 

I think if it's just a simple implementation of an available filter, it should go on docs. The Snippet Library should instead be for more non-obvious uses of filter/actions.

For example, I just added the minimum donation snippet which just uses the give_checkout_error_checks action. But not in an obvious way, so I think that's great.

But the [Custom Donation Total Label](https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/custom-donation-total-label.php) really is just an example of exactly the purpose of that filter and should instead be hosted here:
https://givewp.com/documentation/developers/filters-explanation-and-usage/

@DevinWalker Agree? Disagree?

**Comment by DevinWalker** [comment]
The problem I have with: https://givewp.com/documentation/developers/filters-explanation-and-usage/ is it's not under version control and we'll have code in two places. Can we perhaps have it hosted here and embed them on the site?

**Comment by mathetos** [comment]
Something like this might work for that:
http://www.codediesel.com/javascript/easily-embed-a-github-repo-onto-your-site/

**Comment by mathetos** [comment]
I think we're going to be creating a real Give CODEX eventually, which would resolve this issue completely.

Closing for now.
