### ISSUE TITLE
Create a maximum donation snippet. 

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Snippet-Library#21]
user request for a snippet to prevent donations over a certain amount. (10,000, in this case).

Is that possible with a snippet?

**Comment by mathetos** [comment]
I think so. We could tie it into the "close form" action relatively easily. 

We discussed this A LOT during the election season as a potential Add-on. Limit total donations by user-account and/or email address. Not enough hours in the day.

**Comment by DevinWalker** [comment]
Done: https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/maximum-donation-amount.php
