### ISSUE TITLE
Make the fields required ? 

### ISSUE THREAD

**Issue by akobryan** [WordImpress/Give-Snippet-Library#24]
Hello, 

Is-there a way to make all the fields required ? 
(as the "require last name" snippet does)

Thanks

**Comment by akobryan** [comment]
... My question is about the "add-billing-fields-to-paypal-standard" snippet.
:)

**Comment by DevinWalker** [comment]
You want to make all the billing fields required as well? That's what I'm hearing?

**Comment by akobryan** [comment]
Yes, if possible.

**Comment by DevinWalker** [comment]
You can use this snippet to extend to the fields you need: https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/require-last-name.php
