### ISSUE TITLE
Need snippet for moving Donors choice checkbox

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Snippet-Library#3]
@DevinWalker Can you create a snippet to allow users to move the donors choice checkbox to a different area of the form?

I've tried just removing the checkbox without success:
```
remove_action( 'give_after_main_content', 'give_output_donors_choice_checkbox', 99 );
```

And this:

```
$recurring_class = new Give_Recurring;
global $recurring_class;
remove_action( 'give_after_main_content', array($recurring_class, 'give_output_donors_choice_checkbox'), 99 );
```

**Comment by DevinWalker** [comment]
Here is it: https://github.com/WordImpress/Give-Snippet-Library/blob/master/recurring-donations/reposition-recurring-checkbox.php
