### ISSUE TITLE
feat(donation): allow for splitting donations across multiple causes

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Snippet-Library#34]
## Issue overview

This is a much-requested feature. Donors are far more likely to give once than they are 4 or 5 times back-to-back, so giving them a way to support multiple causes in one transaction would be preferable. 

The best way to describe it is with this example:

### Use Case: churches 
A church as 4 causes, all with separate forms for accounting to be able to keep the data separate.
1. General Fund
2. Missionary A
3. Missionary B
4. Homeless ministry

If a donor wants to give in one donation to all 4 causes, that's not currently possible. This is extremely common in church giving, where the memo line of the check denotes a portion of the giving to each fund.

## Proposed solution:
This will likely require the data restructuring that is coming in 2.0, but some sort of process that sits in between the submission of the donation from the front end and the processing of it on the back end, that splits the donation out to multiple forms, with options to enable receipts for each individual form, or just a receipt for the parent form. 

In this case, we would be creating not even a "form" in the way we think of them, but a sort of "pre-form" that routes donations through forms. 

#### Considerations:
It's likely that sending individual donations through to the gateway back-to-back will cause fraud warnings to go up (either at the gateway, or at the donor's credit card company), so sending money all at once would be preferable (the donor should only see one receipt from the payment gateway, after all. To them, it was one transaction.)

This would create a discrepancy between the gateway logs and the give logs, and would be especially problematic for recurring donations.

**Comment by mathetos** [comment]
The biggest complication with this isn't assigning multiple "funds" but reporting on that in the backend. Because the reporting is crucial for Accounting to know how to divvy up that lump sum and digging through the Donation Details of every donation isn't realistic.

**Comment by Benunc** [comment]
another request for this today

**Comment by Benunc** [comment]
Another request for this today.

**Comment by Benunc** [comment]
a request from Facebook for this:

> Its Great Overview, Just want to Know, If some one want to Donate 2 campaign together, will it add that to the cart like easy digital download do. so that Donation for Water 10$ and Donation for River 20$  in total 30$ can be paid in total together , is this supported with this plugin

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give #3054](https://github.com/WordImpress/Give/issues/3054) via [**ZenHub**](https://www.zenhub.com/)
