### ISSUE TITLE
Snippet for allowing custom recurring amount

### ISSUE THREAD

**Issue by captainhook** [WordImpress/Give-Snippet-Library#39]
# Overview
'Custom amount' option in multi-level donation does not have a recurring option.

When recurring is forced on a form - i.e. set to 'Yes - Admin Defined', all the levels have an option of 'Recurring' (enable/disabling recurring for that level), and 'Period' (how long the subscription runs). However, the 'custom amount' is set as a one-off donation, without any options to force it to be recurring.

# Proposed solution
'Custom amount' in the form editor should have following options:
* Recurring
  * Yes
  * No
* Period
  * Daily
  * Weekly
  * Monthly
  * Yearly
  * Allow user to choose

I'd love to hear some thoughts on this.

**Comment by mathetos** [comment]
Hi @captainhook we plan to resolve this in our Recurring Donations Add-on directly. We won't be providing a snippet because this functionality is too important.

Thanks!
