### ISSUE TITLE
PayPal Billing fields not populating

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Snippet-Library#4]
This snippet adds billing fields to PayPal Standard checkout:
https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/add-pps-billing-fields.php

But it's not populating the name and several other fields in the PayPal form. Making the donation process much more tedious.

**Comment by DevinWalker** [comment]
I guess we don't include this in Core... I thought we did.

**Comment by DevinWalker** [comment]
This brings up the question, should we include this in core? We can provide additional code to send PP the address data...

**Comment by mathetos** [comment]
I think we should and I just added the above issue.

**Comment by mathetos** [comment]
Deleted the file, and closing this out since it is included in Core now.
