### ISSUE TITLE
Snippet for recording Stripe transaction ID in donation belonging to subscription

### ISSUE THREAD

**Issue by captainhook** [WordImpress/Give-Snippet-Library#40]
# Overview
Currently, donations are recorded with the Stripe transaction ID. However, in the case that the donation belongs to a subscription, the donation is missing the Stripe transaction ID, or the "Donation ID" meta as seen on the donation page.

# Issues
I can imagine this causing reconciliation issues, since an 'accountant' would have to reconcile the Give donation export with a Stripe export, match with email addresses to create a final document that they can work off.

# Proposed solution
Capture Stripe transaction ID for donations belonging to Subscriptions, just as it is done for one-off donations.
This would cut out the reconciliation step an accountant would need to do, since the transaction ID would already be in the Give export, and the accountant would not need to reconcile the export against Stripe's export to find the transaction ID.

**Comment by mathetos** [comment]
Hi @captainhook -- this is only an issue if you have not properly configured your Stripe webhook. See our docs here on configuring that:
https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/stripe/

If you have support questions at all, please use our support channel:
https://givewp.com/support

Thanks!
