### ISSUE TITLE
Donation amount does not change in multi-level giving when you click on a different level of donation

### ISSUE THREAD

**Issue by kkellett** [WordImpress/Give-Snippet-Library#41]
Hi, I am working with the Give Core plug-in and having an issue. I have set up my forms with multi-level donations. When I view the site live, you can click on the buttons for each level, but the donation amount displayed at the top and total at the bottom of the page do not change. Please let me know what I can do to fix this. (We have not yet input information for a payment gateway.) The website is www.cisnt.org/match-my-mentor-hours.

Here is the system report:

### WordPress Environment ###

Home URL: http://cisnt.org
Site URL: http://cisnt.org
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Home (#4)
Page for Posts: Blog (#94)
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, acf-disabled, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, confirmed

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: cisnt.org
TLS Connection: Connection uses TLS 1.2
TLS Connection: Bad
Server Info: Apache
PHP Version: 5.6.32
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 64 MB
cURL Version: ❌ 7.24.0, OpenSSL/1.0.0 - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.32
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 1.8.16
Upgraded From: –
Test Mode: Disabled
Currency Code: USD
Currency Position: After
Decimal Separator: .
Thousands Separator: ,
Success Page: http://cisnt.org/donation-confirmation/
Failure Page: http://cisnt.org/donation-failed/
Donation History Page: http://cisnt.org/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Enabled
Donor Email Access: Disabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Advanced Custom Fields: Nav Menu Field: by Faison Zutavern – 2.0.0
Advanced Custom Fields PRO: by Elliot Condon – 5.6.4
Event Organiser: by Stephen Harris – 3.4.1
Event Organiser Pro: by Stephen Harris – 1.11.7
Gravity Forms: by rocketgenius – 2.2.5
Media Library Categories: by Jeffrey-WP – 1.5.6
Wordfence Security: by Wordfence – 6.3.21

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0
Hello Dolly: by Matt Mullenweg – 1.6
Jetpack by WordPress.com: by Automattic – 5.4
MOJO Marketplace: by Mike Hansen – 0.8.2
WooCommerce: by Automattic – 3.2.2

### Active MU Plugins ###

SSO: by Garth Mortensen, Mike Hansen – 0.1

### Theme ###

Name: CISNT
Version: 1.0
Author URL: http://www.cmdtab.co
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

**Comment by Benunc** [comment]
Hi there,

This repository is not designed to be a support channel. Please direct all support enquiries to https://givewp.com/support

That said, this sounds like a jQuery issue, that the built in jQuery is being overridden by the theme or another plugin. To confirm, deactivate other plugins and/or the theme to confirm that something is not playing nicely with Give. You can also try moving the scripts to the footer (in DOnations > Settings > Advanced, or disabling the floating labels in Donations > Settings> Display options.

If you have further questions or clarifications, please use an official support channel. 

Thanks!
