### ISSUE TITLE
Address fields after name/email

### ISSUE THREAD

**Issue by manattweb** [WordImpress/Give-Snippet-Library#42]
How do I add the fields from mailing-address-custom-fields to the end of the form rather than at the beginning?

**Comment by DevinWalker** [comment]
Which snippet are you talking about exactly? Also, the preferred place to ask questions not related to code issues is https://wordpress.org/support/plugin/give

**Comment by manattweb** [comment]
I told you - it's the "mailing-address-custom-fields" - one of the PHP snippets in this repository. I implemented it using the snippets plugin and it put the Mailing Address fields before the Personal Information fields and I need to know how to reverse them. This isn't a support question about Give, it's about the PHP code.

**Comment by DevinWalker** [comment]
What you would do is switch the action from the one here: https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/mailing-address-custom-fields.php#L159

To the one that fires at the appropriate location. For your case I would say all you need to do is change the action to a lower priority so they are switched around:

`add_action( 'give_after_donation_levels', 'my_prefix_give_mailing_fields', 15, 1 );`

**Comment by manattweb** [comment]
much thanks

**Comment by manattweb** [comment]
This didn't work. Do you have any other ideas?

**Comment by mathetos** [comment]
Hi @manattweb can you provide the code you are working with that didn't work? We can have much more insight if we have something to test directly.

**Comment by manattweb** [comment]
It's the exact code found in the snippet described above and taken from this repository. I just copied and pasted and while it adds the needed fields, it puts them above the name and email and I'd like to know if there's a way to reverse the order and put the mailing fields below the name/email fields.

**Comment by mathetos** [comment]
Try using this action instead: `give_donation_form_after_personal_info`

A good tool to see and understand the hooks in Give forms is our Give Hook Helper, which you can download here: https://github.com/WordImpress/Give-Hook-Helper

Thanks!

**Comment by manattweb** [comment]
Mathetos - thanks for the reply. Where would that action be placed - can you give me a line number?

**Comment by mathetos** [comment]
Line 159, the same that Devin pointed out above. It would replace `'give_after_donation_levels'` here:
https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/mailing-address-custom-fields.php#L159

**Comment by manattweb** [comment]
Boom! So much thanks - is it clear I'm not a PHP coder?

**Comment by DevinWalker** [comment]
No worries @manattweb - if you like our plugin/support please consider rating it: https://wordpress.org/support/plugin/give/reviews/
