### ISSUE TITLE
create snippet to check for active suscription

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Snippet-Library#46]
Customers sometimes want to find only users who have an active subscription. (to display certain content, or perform other tasks)

I see Give_Recurring_Subscriber->has_active_subscription() in the code, so I assume there is a way to create that.

**Comment by ravinderk** [comment]
@raftaar1191 please check if we have a helper function to get an active subscription or not if not then I will move this to recurring addon because it will be a good addition to API.

**Comment by ravinderk** [comment]
Close in favor of https://github.com/WordImpress/Give-Recurring-Donations/issues/513
