### ISSUE TITLE
[Give 2.0] Search and create issues to update snippets if needed

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Snippet-Library#48]

**Comment by mathetos** [comment]
@ravinderk To help with this process, here's some that I know need updating:

- [ ] https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/custom-currency.php
- [ ] https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/custom-fields-plugin.php
