### ISSUE TITLE
[Give 2.0] Use Give_Payment_Query in snippets

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Snippet-Library#51]
https://github.com/WordImpress/Give-Snippet-Library/tree/master/useful-queries

**Comment by raftaar1191** [comment]
Slack Chat Summary

Participants: @raftaar1191 , @ravinderk
Topic: Remove Default WordPress WP_Query
Result: Will remove all the default function if we have the same function in Give Core
