### ISSUE TITLE
[Give 2.0] Use email api to check email enabled or not instead of give_admin_notices_disabled

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Snippet-Library#53]
https://github.com/WordImpress/Give-Snippet-Library/tree/master/email-customization

**Comment by raftaar1191** [comment]
Slack Chat Summary

Participants: @raftaar1191 , @ravinderk
Topic: What Changes I have to doo
Result: Remove the function `give_admin_notices_disabled ` and replace it with the new function that are being add on Give Core 2.0
