### ISSUE TITLE
[Give 2.0] deprecated new user notification stopping snippet

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Snippet-Library#56]
https://github.com/WordImpress/Give-Snippet-Library/blob/master/email-customization/remove-new-user-notification.php

**Comment by ravinderk** [comment]
@mathetos @DevinWalker We can stop email notification within core setting. Let me know what do you think.

**Comment by DevinWalker** [comment]
What do you mean by that? A setting or a filter? I would prefer this just be a snippet and we move on from it.

**Comment by ravinderk** [comment]
@DevinWalker Alright. I am closing this issue.
