### ISSUE TITLE
feat(snippet): demonstrate how to save custom field as donor meta

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Snippet-Library#74]
As a Give Developer I want to have a clear example of how I can create a custom field in my forms that populates Donor Meta, not donation meta. 

A perfect example is a phone number. This wouldn't be related to the donation at all, not required for the monetary transaction in any way. So i want to store it as donor meta.

Bonus points if we can check if a value already exists and add a second value if it's different from the existing value.

**Comment by kevinwhoffman** [comment]
@ravinderk Please work this into your next sprint using the phone number example that @mathetos suggested.

**Comment by DevinWalker** [comment]
Looks good to me @ravinderk - closing
